workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: "Precache & Install Pods"
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: "Build iOS Release"
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      # Instruct Codemagic to publish via App Store Connect using
      # the API key defined in the top-level code_signing block
      app_store_connect:
        inherit: true
        export_method: app-store

# Move code signing credentials to top-level
code_signing:
  app_store_connect:
    # Instead of apple_id/password, use API key-based auth:
    # 1) key_id => The Key ID (e.g. "4P3J9NG42Y")
    # 2) issuer_id => The Issuer ID from App Store Connect
    # 3) private_key => The entire content of the .p8 file
    key_id: $APP_STORE_CONNECT_KEY_ID
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    private_key: $APP_STORE_CONNECT_PRIVATE_KEY

  xcode_project:
    automatic_code_signing: true
    bundle_id: "com.ragtag.ragtag"
