workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: "Precache & Install Pods"
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: "Build iOS Release"
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    # Publishing block only needs the export method, 
    # code signing is set in the separate code_signing block below.
    publishing:
      ios:
        export_method: app-store

    # Here's the correct place for auto code signing + Apple ID credentials
    code_signing:
      app_store_connect:
        # Apple ID email (the one you use to log into App Store Connect)
        apple_id: $APPLE_ID  
        
        # MUST be your app-specific password if you have 2FA on your Apple ID
        # (Generate it at appleid.apple.com -> Security -> App-Specific Passwords)
        password: $APPLE_PASSWORD
        
        # If you have multiple teams in Apple Developer, uncomment:
        # team_id: $TEAM_ID

      xcode_project:
        # Tells Codemagic to handle provisioning profiles automatically
        automatic_code_signing: true

        # Make sure this bundle_id matches your app's Info.plist / Xcode config
        bundle_id: "com.ragtag.ragtag"
