workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: stable
      xcode: latest

      # Import the variable group named "Nicholas Cooke"
      groups:
        - "Nicholas Cooke"

    scripts:
      - name: "Precache & Install Pods"
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: "Build iOS Release"
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # Tells publishing to inherit the credentials from the top-level code_signing block
        inherit: true
        export_method: app-store

# Top-level code signing configuration
code_signing:
  app_store_connect:
    # References the environment variables from your "Nicholas Cooke" group
    key_id: $APP_STORE_CONNECT_KEY_ID
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    private_key: $APP_STORE_CONNECT_PRIVATE_KEY

  xcode_project:
    automatic_code_signing: true

    # Must match your app's bundle identifier in Xcode
    bundle_id: "com.ragtag.ragtag"
