workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: "Precache & Install Pods"
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: "Build iOS Release"
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # Tells the publishing config to use the credentials set in code_signing
        inherit: true
        
        # "app-store", "ad-hoc", "enterprise", or "development"
        export_method: app-store

# The top-level code_signing block where your Apple ID + password go
code_signing:
  app_store_connect:
    # The Apple ID email you use to sign in to App Store Connect
    apple_id: $APPLE_ID

    # Must be an "app-specific password" if you have 2FA enabled on your Apple ID
    # Generate one at https://appleid.apple.com/ under "Security"
    password: $APPLE_PASSWORD

    # If you have multiple Apple Developer teams, uncomment:
    # team_id: $TEAM_ID

  xcode_project:
    # Tells Codemagic to generate provisioning profiles automatically
    automatic_code_signing: true

    # Must match your project's Bundle ID (ios/Runner.xcworkspace > Signing & Capabilities)
    bundle_id: "com.ragtag.ragtag"
