workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Precache iOS
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build iOS Release
        script: |
          # Option A: Build an .xcarchive for iOS
          # flutter build ios --release

          # Option B: Build a distributable .ipa for iOS
          flutter build ipa --release
