workflows:
  build_and_publish_ios:
    name: Build and Publish iOS IPA
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        DEVELOPMENT_TEAM: "88KTK78D9T"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_ID: $APP_STORE_CONNECT_KEY_ID
    scripts:
      - echo "Running Flutter Doctor..."
      - flutter doctor -v
      - echo "Pre-caching iOS artifacts..."
      - flutter precache --ios
      - echo "Cleaning project..."
      - flutter clean
      - flutter pub get
      - echo "Building iOS release without codesign..."
      - flutter build ios --release --no-codesign
      - cd ios
      - echo "Archiving the app..."
      # Archive the app; note the DEVELOPMENT_TEAM and flags for allowing provisioning updates
      - xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM -allowProvisioningUpdates -allowProvisioningDeviceRegistration
      - echo "Removing embedded provisioning profile from App.framework..."
      # Remove the embedded provisioning profile from the framework to avoid signing errors
      - rm -f build/Runner.xcarchive/Products/Applications/Runner.app/Frameworks/App.framework/embedded.mobileprovision
      - echo "Exporting IPA..."
      - xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportPath build/ipa -exportOptionsPlist exportOptions.plist DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM -allowProvisioningUpdates
    artifacts:
      - ios/build/ipa/*.ipa
    publishing:
      app_store_connect:
        # The API key for App Store Connect (private key, issuer, and key id are required)
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        api_key_id: $APP_STORE_CONNECT_KEY_ID
