# Top-level code_signing and workflows are siblings
workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: "Install Pods"
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: "Build iOS Release"
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # Tells publishing to use the API key from 'code_signing' below
        inherit: true
        export_method: app-store

# MAKE SURE this code_signing block is NOT nested under workflows
code_signing:
  app_store_connect:
    key_id: $APP_STORE_CONNECT_KEY_ID            # e.g. "4P3J9NG42Y"
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # e.g. "12ab34cd-5678-90ef-1234-5abc6789de01"
    private_key: $APP_STORE_CONNECT_PRIVATE_KEY  # Entire .p8 file contents (including BEGIN/END lines)

  xcode_project:
    automatic_code_signing: true
    bundle_id: "com.ragtag.ragtag"
