workflows:
  ios-workflow:
    name: "iOS Workflow"
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: "Precache & Install Pods"
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: "Build iOS Release"
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    # Here's where we configure publishing to App Store Connect
    publishing:
      app_store_connect:
        export_method: app-store
        # Optionally:
        # submit_to_testflight: true
        # should_auto_submit_app_store_version: true
        # release_type: MANUAL

# Everything related to code signing goes into this top-level code_signing section
code_signing:
  app_store_connect:
    # The Apple ID email you use to sign in to App Store Connect
    apple_id: $APPLE_ID

    # If you use Apple ID + password for authentication (vs. API key),
    # you must provide an app-specific password here (2FA-enabled Apple IDs).
    password: $APPLE_PASSWORD

    # If you're in multiple Apple Developer teams, specify:
    # team_id: $TEAM_ID

  xcode_project:
    # Tells Codemagic to handle provisioning profiles automatically
    automatic_code_signing: true

    # Must match the Bundle Identifier in Xcode (ios/Runner.xcworkspace)
    bundle_id: "com.ragtag.ragtag"
