platform :ios, '13.0'

# CocoaPods analytics sends network stats (optional)
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Load Flutter's pod helper (this is required for Flutter to work with CocoaPods)
require File.expand_path(File.join('Flutter', 'podhelper.rb'), __dir__)

target 'Runner' do
  use_frameworks!

  # This ensures that Flutter dependencies are correctly installed
  flutter_install_all_pods(File.dirname(File.realpath(__FILE__)))

  # Additional Pods you may need (e.g., Firebase)
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  end