platform :ios, '13.0'

use_frameworks!

# Relative path to the Flutter project root
flutter_application_path = '../../'

# Load Flutter's pod helper (this is required for Flutter to work with CocoaPods)
require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __dir__)

target 'Runner' do
  use_frameworks!

  # This ensures that Flutter dependencies are correctly installed
  flutter_install_all_pods(File.dirname(File.realpath(__FILE__)))
  
  # Additional Pods you may need (e.g., Firebase)
  # pod 'Firebase/Core'
  # pod 'Firebase/Firestore'
end
