name: ios
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ">=3.6.1 <4.0.0"

# Ensure version and build number consistency across platforms

flutter:
  uses-material-design: true

  assets:
    - assets/ragtaglogo.png
    - assets/welcomepageart.png
    - assets/back_button_image.png
    - assets/icon.png
    - assets/splash_bg.png

    # Add all your assets here including the app icon

  fonts:
    - family: Lovelo
      fonts:
        - asset: assets/fonts/Lovelo-Black.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200

flutter_native_splash:
  image: assets/splash_bg.png
  color: "#000000"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
